Merged with release-3-2-4.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21,7 +21,7 @@
 # 4. Macros for locating various systems (Matlab, etc.)
 # 5. Macros used to test things about the computer/OS/hardware
 #
-# $Id: configure,v 1.20 2001/09/28 23:19:43 jimg Exp $
+# $Id: configure,v 1.21 2001/10/14 01:36:17 jimg Exp $
 
 # 1. Unidata's macros
 #-------------------------------------------------------------------------
@@ -894,8 +894,8 @@ host_os=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 echo "$ac_t""$host" 1>&6
 
 
-CFLAGS="-gstabs -O2 $CFLAGS"
-CXXFLAGS="-gstabs -O2 $CXXFLAGS"
+CFLAGS=${CFLAGS-"-gstabs -O2 $CFLAGS"}
+CXXFLAGS=${CXXFLAGS-"-gstabs -O2 $CXXFLAGS"}
 
 # Extract the first word of "gcc", so it can be a program name with args.
 set dummy gcc; ac_word=$2
@@ -1334,7 +1334,7 @@ fi
 	    then
 		echo "$ac_t""Found perl version ${perl_ver}." 1>&6
 	    else
-		{ echo "configure: error: perl version: found ${perl_ver} should be at least 5.000." 1>&2; exit 1; }
+		{ echo "configure: error: *** perl version: found ${perl_ver} should be at least 5.000." 1>&2; exit 1; }
 	    fi
 	    ;;
 	*)
@@ -2341,7 +2341,7 @@ EOF
 	XDR_INT32=xdr_int
 	XDR_UINT32=xdr_u_int
     else
-	{ echo "configure: error: How do I get a 32 bit integer on this machine?" 1>&2; exit 1; }
+	{ echo "configure: error: *** How do I get a 32 bit integer on this machine?" 1>&2; exit 1; }
     fi
     # I'm using the three arg form of AC_DEFINE_UNQUOTED because autoheader
     # needs the third argument (although I don't quite get the specifics... 
@@ -2389,7 +2389,7 @@ EOF
     then
 	DODS_BYTE="unsigned char"
     else
-	{ echo "configure: error: How do I get an 8 bit unsigned integer on this machine?" 1>&2; exit 1; }
+	{ echo "configure: error: *** How do I get an 8 bit unsigned integer on this machine?" 1>&2; exit 1; }
     fi
     cat >> confdefs.h <<EOF
 #define DBYTE $DODS_BYTE
@@ -2403,7 +2403,7 @@ EOF
 	XDR_FLOAT64=xdr_double
 	XDR_FLOAT32=xdr_float
     else
-	{ echo "configure: error: How do I get floating point types on this machine?" 1>&2; exit 1; }
+	{ echo "configure: error: *** How do I get floating point types on this machine?" 1>&2; exit 1; }
     fi
     cat >> confdefs.h <<EOF
 #define DFLOAT64 $DODS_FLOAT64
@@ -2422,14 +2422,14 @@ EOF
 EOF
 
 
-    echo $ac_n "checking "for the packages directory"""... $ac_c" 1>&6
-echo "configure:2427: checking "for the packages directory"" >&5
+    echo $ac_n "checking for the packages directory""... $ac_c" 1>&6
+echo "configure:2427: checking for the packages directory" >&5
     # Where does DODS live?
     
     DODS_PACKAGES_DIR=`ls -1d ${dods_relative}src/packages* 2> /dev/null`
     if test -z "$DODS_PACKAGES_DIR"
     then
-	{ echo "configure: error: "Could not find the third-party packages!"" 1>&2; exit 1; }
+	{ echo "configure: error: *** Could not find the third-party packages!" 1>&2; exit 1; }
     fi
     echo "$ac_t""$DODS_PACKAGES_DIR" 1>&6
     LDFLAGS="$LDFLAGS -L${dods_relative}lib"
@@ -2852,7 +2852,7 @@ EOF
 
       ;;
     *)
-      { echo "configure: error: Bad debug value" 1>&2; exit 1; }
+      { echo "configure: error: *** Bad debug value" 1>&2; exit 1; }
       ;;
     esac
 
